[tox]
envlist = py3,py{38,39,310,311,312,313}
skipsdist = True

[testenv]
deps =
    pytest
    termcolor
commands =
    pytest {posargs}

[testenv:lint]
deps =
    black
    isort
    flake8
commands =
    black --check bin/ tests/
    isort --check-only bin/ tests/
    flake8 bin/ tests/
